### ISSUE TITLE
Invalid webpart property text

### ISSUE THREAD

**Issue by bkehren** [KenticoDevTrev/RelationshipsExtended#9]
When viewing the list of pages related to a given page, some invalid text displays.  

Text displayed:

**_This page is related to test_**

The solution is to update the "Edit relationship" page template under Administration Interface > Page Templates > UI templates > Edit in the Kentico Xperience UI.  Modifying the "Read Only Listing (Ad Hoc Right only)" web part on the Design tab and changing the Content Before value from:

**`<h3>This page is related to test</h3>`**

to 

**`<h3>This Page Is Related To:</h3>`**

removes the text "test" from the UI.

**Comment by KenticoDevTrev** [comment]
Thanks, i was able to remove this a while back, sorry i don't see these...
